<a href="https://colab.research.google.com/github/ehfk45/Colab-/blob/main/%ED%9A%8C%EA%B8%B0%EB%AA%A8%EB%8D%B8_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
# sklearn 데이터분할 함수 임포트
from sklearn.model_selection import train_test_split


# sklearn OneHotEncoder 임포트
from sklearn.preprocessing import OneHotEncoder


# 회귀모델들 임포트 모델비교시 사용
# 3개 거리, 선형, 트리 #
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor


# 회귀평가지표 함수 임포트
# 4개 #
from sklearn.metrics import r2_score, maen_absolute_error, maan_squared_error, root_mean_squared_error

In [ ]:
train = pd.DataFrame({
    "building_type": [
        "office","office","retail","hospital","school",
        "office","retail","school","hospital","office",
        "retail","office","school","hospital","office",
        "retail","school","office","hospital","retail",
        "office","school","retail","hospital","office",
        "school","retail","office","hospital","office"
    ],

    "area": [
        1200,1800,950,2500,2100,
        1500,1100,2800,3200,1400,
        900,2200,1900,3500,1700,
        1300,2400,2000,2800,1000,
        1600,3000,1250,4000,2300,
        1800,1050,2600,3100,1900
    ],

    "age": [
        5,12,8,20,15,
        7,18,10,25,6,
        14,9,22,30,11,
        4,16,13,19,8,
        10,17,6,28,14,
        9,21,12,18,7
    ],

    "floors": [
        5,8,3,10,4,
        6,3,5,12,7,
        2,9,4,15,6,
        3,5,7,11,4,
        8,6,3,14,9,
        5,2,10,8,6
    ],

    "cooling_area": [
        900,1300,700,1800,1500,
        1100,800,1900,2300,1000,
        650,1600,1300,2500,1200,
        900,1700,1400,2000,700,
        1200,2100,900,2900,1600,
        1300,750,1800,2200,1400
    ],

    "operation_hours": [
        10,12,11,18,8,
        10,13,9,24,11,
        12,14,8,24,10,
        12,9,8,20,11,
        13,7,12,24,10,
        8,13,11,18,12
    ],

    "employees": [
        80,120,60,300,150,
        95,70,180,420,100,
        55,160,130,500,110,
        75,200,140,350,65,
        105,220,80,600,170,
        160,50,190,380,125
    ],

    "electricity": [
        18200,26500,14800,52000,23800,
        22100,17100,30100,68000,20500,
        13200,34200,21400,79000,24900,
        17600,28600,24500,61500,15400,
        23200,32500,16100,91000,35400,
        25100,13900,39200,70500,28900
    ]
})

# 평가 데이터
# 평가 데이터에는 electricity가 없다. -> 예측
test = pd.DataFrame({
    "building_type": [
        "office","retail","hospital","school",
        "office","retail","hospital","office",
        "school","retail"
    ],

    "area": [
        1900,1050,2900,2200,
        1550,1350,3700,2400,
        2600,850
    ],

    "age": [
        9,16,18,12,
        5,11,27,14,
        8,20
    ],

    "floors": [
        7,3,11,5,
        6,4,13,9,
        6,2
    ],

    "cooling_area": [
        1350,750,2100,1600,
        1150,950,2700,1750,
        1900,600
    ],

    "operation_hours": [
        11,12,24,9,
        10,13,24,12,
        8,11
    ],

    "employees": [
        130,65,350,160,
        100,85,550,180,
        210,55
    ]
})

In [ ]:
train

,building_type,area,age,floors,cooling_area,operation_hours,employees,electricity
0,office,1200,5,5,900,10,80,18200
1,office,1800,12,8,1300,12,120,26500
2,retail,950,8,3,700,11,60,14800
3,hospital,2500,20,10,1800,18,300,52000
4,school,2100,15,4,1500,8,150,23800
5,office,1500,7,6,1100,10,95,22100
6,retail,1100,18,3,800,13,70,17100
7,school,2800,10,5,1900,9,180,30100
8,hospital,3200,25,12,2300,24,420,68000
9,office,1400,6,7,1000,11,100,20500


In [ ]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   building_type    30 non-null     object
 1   area             30 non-null     int64 
 2   age              30 non-null     int64 
 3   floors           30 non-null     int64 
 4   cooling_area     30 non-null     int64 
 5   operation_hours  30 non-null     int64 
 6   employees        30 non-null     int64 
 7   electricity      30 non-null     int64 
dtypes: int64(7), object(1)
memory usage: 2.0+ KB


In [ ]:
train['building_type'].unique()

array(['office', 'retail', 'hospital', 'school'], dtype=object)

In [ ]:
test['building_type'].unique()

array(['office', 'retail', 'hospital', 'school'], dtype=object)

In [ ]:
train['building_type'].value_counts()

,count
building_type,
office,11
retail,7
hospital,6
school,6


In [ ]:
test['building_type'].value_counts()

,count
building_type,
office,3
retail,3
hospital,2
school,2


In [ ]:
from IPython.lib.display import YouTubeVideo
# ============================================================
# 1. X, y 분리 (특성과 타겟 나누기)
# ============================================================


# train 과 test 원본 유지
#
X = train.drop('electricity', axis = 1) # Y열을 삭제한 데이터셋 -> DataFrame
y = train['electricity'] # Y열만 -> 시리즈

display(X.head())
display(Y.head())

X_test = test.copy()

,building_type,area,age,floors,cooling_area,operation_hours,employees
0,office,1200,5,5,900,10,80
1,office,1800,12,8,1300,12,120
2,retail,950,8,3,700,11,60
3,hospital,2500,20,10,1800,18,300
4,school,2100,15,4,1500,8,150


,electricity
0,18200
1,26500
2,14800
3,52000
4,23800


In [ ]:
# ============================================================
# 2. 학습 / 검증 데이터 분리 (누수 방지를 위해 인코딩 전 분할)
# ============================================================

# 반환값은 언패킹해서 4개의 변수에 대입

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size= 0.2, random_state=42)

display(len(X_train))
display(len(X_val))
display(len(y_train))
display(len(y_val))


24

6

24

6

In [ ]:
# ============================================================
# 3. 전처리 인코딩
# ============================================================

# OneHotEncoder()
# 새로운 변수추가로 발생하는 에러는 무시

ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')


#fit_transform() + 3qjs(X_train, X_val, X_test)
# 열추가하는 데이터프레임 + numpy 배열이므로 numpy.stack(), pandas.concat() api + 3번


# 1) [학습 데이터] 인코딩 결과 배열 + 나머지 수치형 배열을 그냥 가로로 합체!
X_train_cat = ohe.fit_transform(X_train[['building_type']])
print(X_train_cat)


# 2) [검증 데이터] 동일하게 처리 (fit은 절대 하지 않음!)
X_train_cat = ohe.fit_transform(X_val[['building_type']])

# 3) [테스트 데이터] 동일하게 처리
X_train_cat = ohe.fit_transform(X_test[['building_type']])



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]


NameError: name 'X_val_cat' is not defined